spring.application.name=allthings


spring.datasource.url=jdbc:postgresql://localhost:5432/db_allthings
spring.datasource.username=postgres
spring.datasource.password=postdba


spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

spring.jpa.show-sql=true
